HEARTBEAT:
   output: -1
ATTITUDE:
   output: 1
   input: 1
SYS_STATUS:
   output: 1
GLOBAL_POSITION_INT:
   output: 1
GPS_RAW_INT:
   output: 0
AHRS:
   output: 1
POWER_STATUS:
   output: 1
HWSTATUS:
   output: 1
ALL:
   output: 0
